### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by nnhhoang** [yd-kwon/MatNet#7]
max_aug_pomo_reward, _ = max_pomo_reward.max(dim=0)  # get best results from augmentation
            # shape: (batch,)
aug_score = -max_aug_pomo_reward.float().mean()  # negative sign to make positive value

I want to ask why you use .mean() but we want to get the best result

**Comment by yd-kwon** [comment]
the mean is for averaging over (a batch of) different problems. The code solves different problems in parallel for speed.
 max_pomo_reward.max(dim=0) is where we get the best result for each problem instance.
