### ISSUE TITLE
I want ask a question?

### ISSUE THREAD

**Issue by nnhhoang** [yd-kwon/MatNet#8]
Sorry because i dont understand the code and I need your help ! I have two question
- The first question: I understand that the score and aug_score is the tour length. But went i test it with my own dataset, i change the scale so the ans is different. So i want to ask that the train scale and test scale must be the same ?
- The second question: I know that max_pomo_reward.max(dim=0) is the best tour and I dont know how to get it, and I know self.env.slected_node_list is the tour but how i can get it from the best tour ?
TKS!!

**Comment by yd-kwon** [comment]
1) yes. the scales should be the same.
2) "max" function returns a namedtuple (values, indices). Use the indices to extract the good tour from the selected_node_list.
